version: "3"
services:
  sando-website:
    network_mode: host
    container_name: sando-website
    restart: "unless-stopped"
    image: sando-website:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/sando-website:/database
    environment: 
      - TZ=Asia/Tokyo
      - SANDO_API_BASE_URL=http://192.168.49.80:8044